# Generated by Django 4.0.3 on 2023-01-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_keywordid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywordid',
            old_name='Id',
            new_name='keyword',
        ),
    ]
